version: 1.0.{build}
image: Visual Studio 2017
matrix:
  fast_finish: true



before_build:
- ps: >-
    nuget restore

    choco install opencover.portable --no-progress

    choco install codecov --no-progress
- sh: >-
    mkdir ./com_tmp_dir                                         && \
    cd ./com_tmp_dir                                            && \
    curl -sS http://files.akeo.ie/blog/com0com.7z > com0com.7z  && \
    unzip com0com.7z                                            && \
    ./x64/setupc.exe --silent install portname=COM1 portname=COM2
# - ps: >-
#     nuget restore

#     choco install opencover.portable --no-progress

#     choco install codecov --no-progress

#     choco install com0com --no-progress



# - sh: >-
#     # nuget restore

#     # choco install opencover.portable --no-progress    && \
#     # choco install codecov --no-progress

# # intall com0com https://pete.akeo.ie/2011/07/com0com-signed-drivers.html
#     mkdir ./com_tmp_dir                                         && \
#     cd ./com_tmp_dir                                            && \
#     curl -sS http://files.akeo.ie/blog/com0com.7z > com0com.7z  && \
#     unzip com0com.7z                                            && \
#     ./x64/setupc.exe --silent install portname=COM1 portname=COM2

# - ps: >-
#     Invoke-WebRequest "https://raw.githubusercontent.com/Raggles/com0com/master/com0com/driver/com0com/com0com.inf" -OutFile "C:\projects\qcomm\com0com.inf"

#     Invoke-WebRequest "https://raw.githubusercontent.com/Raggles/com0com/master/com0com/driver/com0com/cncport.inf" -OutFile "C:\projects\qcomm\cncport.inf"

#     Invoke-WebRequest "https://raw.githubusercontent.com/Raggles/com0com/master/com0com/driver/com0com/comport.inf" -OutFile "C:\projects\qcomm\comport.inf"

#     & "C:\Program Files (x86)\com0com\setupc.exe" --silent install portname=COM1 portname=COM2
build:
  verbosity: minimal



test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:".\QComm.UnitTest\bin\Debug\netcoreapp2.1\QComm.UnitTest.dll" -filter:"+[QComm*]* -[QComm.UnitTest]*" -output:".\QComm_coverage.xml" -oldstyle
after_test:
- ps: >-
    codecov -f ".\QComm_coverage.xml"



artifacts:
- path: '\QComm\bin\Debug\QComm.*.nupkg'



deploy:
- provider: NuGet
  api_key:
    secure: OXY8QfF92dsRyE6eiaFMzaYI6YvA/NUsoI+lOPsE2gSB7LGIlvfiHg1Tt0HOTdwU
  on:
    APPVEYOR_REPO_TAG: true
