version: 1.0.{build}
image: Visual Studio 2017
matrix:
  fast_finish: true
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))



before_build:
# intall com0com https://pete.akeo.ie/2011/07/com0com-signed-drivers.html
- ps: choco install autoit.commandline --no-progress
- ps: choco install 7zip.install --no-progress
- ps: mkdir ./com_tmp_dir
- ps: Invoke-WebRequest "http://files.akeo.ie/blog/com0com.7z" -OutFile "./com_tmp_dir/com0com.7z"  
- ps: 7z x ./com0com.7z -y
- ps: cd ./com_tmp_dir/x64
- ps: AutoIt3 "C:\projects\qcomm\setupc_by_autoit.au3"
# install test tootls
- ps: cd "C:\projects\qcomm\"
- ps: nuget restore -Verbosity quiet
- ps: choco install opencover.portable --no-progress
- ps: choco install codecov --no-progress
build:
  verbosity: minimal



test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:".\QComm.UnitTest\bin\Debug\netcoreapp2.1\QComm.UnitTest.dll" -filter:"+[QComm*]* -[QComm.UnitTest]*" -output:".\QComm_coverage.xml" -oldstyle
after_test:
- ps: >-
    codecov -f ".\QComm_coverage.xml"



artifacts:
- path: '.\QComm\bin\Debug\QComm.*.nupkg'



deploy:
- provider: NuGet
  api_key:
    secure: OXY8QfF92dsRyE6eiaFMzaYI6YvA/NUsoI+lOPsE2gSB7LGIlvfiHg1Tt0HOTdwU
  on:
    APPVEYOR_REPO_TAG: true
