version: 1.0.{build}
image: Visual Studio 2017



matrix:
  fast_finish: true



before_build:
- ps: >-
    nuget restore

    choco install opencover.portable --no-progress

    choco install codecov --no-progress
build:
  verbosity: minimal
test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:".\QComm.UnitTest\bin\Debug\netcoreapp2.1\QComm.UnitTest.dll" -filter:"+[QComm*]* -[QComm.UnitTest]*" -output:".\QComm_coverage.xml" -oldstyle

    codecov -f ".\QComm_coverage.xml"
artifacts:
- path: '\QComm\bin\Debug\QComm.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: OXY8QfF92dsRyE6eiaFMzaYI6YvA/NUsoI+lOPsE2gSB7LGIlvfiHg1Tt0HOTdwU
  on:
    APPVEYOR_REPO_TAG: true
