version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: >-
    nuget restore

    choco install opencover.portable --no-progress

    choco install codecov --no-progress
build:
  verbosity: minimal
test_script:
- ps: >-
    OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:".\QComm.UnitTest\bin\Debug\netcoreapp2.1\QComm.UnitTest.dll" -filter:"+[QComm*]* -[QComm.UnitTest]*" -output:".\QComm_coverage.xml" -oldstyle

    codecov -f ".\QComm_coverage.xml"
artifacts:
- path: '\QComm\bin\Debug\QComm.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: {nuget_api_key}
  on:
    APPVEYOR_REPO_TAG: true


environment:
  nuget_api_key:
    secure: RBUST2uIq71U0RWwSdKSkE3m+Pw9yRdnU6XfvuA62CqLfcjFdu/Z6g1CSVxKmyw0DHva4e1amnX8Y2pmhrjf5WFPjAiV6oyY/wOZsmP+Kks=
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt path-to\encrypted-filename.ext.enc -secret %my_secret%
  - sh: ./appveyor-tools/secure-file -decrypt path-to/encrypted-filename.ext.enc -secret $my_secret
matrix:
  fast_finish: true